WIP / Experimental: Enable / Disable text actions
gsantner/markor pull request #1087
Opened 2020-10-12 04:38 UTC by harshad1

This PR adds support for enabling / disabling text actions. Actions are disabled by means of a switch in the reorder actions activity.

This is necessary as it would be good to add actions without cluttering up the actions bar.

![image](https://user-images.githubusercontent.com/1940940/95705845-136c4100-0c0a-11eb-9984-b1cea6679a3c.png)

2020-10-12 07:33 UTC, gsantner commented
I would go for visible/invisible and its icon instead. For the reason, enable could also mean "still visible, but not clickable".

2020-10-12 08:05 UTC, BeayemX commented
Maybe use the terms Show/Hide?

2020-10-12 11:15 UTC, gsantner commented
I already started typing something along "OK".  
But as I thought more about it, I got into mind that like I remembered that likley the bad thing will happen that things overlap or are cut-off. As a person reading primary english you won't experience that, but on german for example you get "Anzeigen/Verstecken" instead of short "Show/Hide".  
...So, when making it Show/Hide it will be a issue when gets localized.

![Unbenannt](https://user-images.githubusercontent.com/6735650/95740331-933aef80-0c8c-11eb-982a-4fc79b2e6ae5.png)

Thus, use icons only, no text. If required, with long-press tooltip set like "toggle visiblity".

2020-10-12 11:16 UTC, gsantner reviewed
I already started typing something along "OK".  
But as I thought more about it, I got into mind that likley the bad thing will happen with overlap and cut-offs. As a person reading primary english you won't experience that, but on german for example you get "Anzeigen/Verstecken" instead of short "Show/Hide".  
...So, when making it Show/Hide it will be a issue when gets localized.

![Unbenannt](https://user-images.githubusercontent.com/6735650/95740331-933aef80-0c8c-11eb-982a-4fc79b2e6ae5.png)

Thus, use icons only, no text. If required, with long-press tooltip set like "toggle visiblity".

2020-10-12 22:39 UTC, harshad1 commented
@gsantner Good point.

I have removed the label and added a tooltip.

2020-10-12 23:27 UTC, harshad1 commented on app/src/main/java/net/gsantner/markor/activity/DocumentEditFragment.java
> +            ((HorizontalScrollView) _textActionsBar.getParent()).setVisibility(View.VISIBLE);
I am not able to get the textactions bar to hide. There is always a band visible. Any suggestions here would be appreciated.

2020-10-14 23:17 UTC, gsantner commented
>  Disable text actions bar if all actions are disabled

Please don't do that. We already had that in the past and it happend to work bad on various "cheap" devices. Also textactions is a major feature of Markor..:D

2020-10-15 01:33 UTC, harshad1 commented
> Please don't do that. We already had that in the past and it happend to work bad on various "cheap" devices. Also textactions is a major feature of Markor..:D
> 
> When all is unchecked and zero items to show, just have a empty bar.

:+1

2020-10-15 01:34 UTC, harshad1 commented
This is ready for testing and merging

2020-10-15 08:19 UTC, gsantner requested changes
@harshad1 

we have quite some duplication and unused things there:

```
private final Set<String> _disabled;



    private void saveNewOrder() {
        final ArrayList<String> disabledKeys = new ArrayList<>();
        _textActions.saveDisabledActions(new ArrayList<>(_adapter._disabled));


        public boolean getEnabled() {
            return _enabled.isChecked();
        }
```


![grafik](https://user-images.githubusercontent.com/6735650/96096074-b6a1ac80-0ecf-11eb-87bf-188a94d5c5c3.png)
![grafik](https://user-images.githubusercontent.com/6735650/96096093-bd302400-0ecf-11eb-9dbc-447d268b3d24.png)

Can you please remove duplicates / clean that?

2020-10-15 15:38 UTC, harshad1 commented on app/src/main/java/net/gsantner/markor/activity/DocumentEditFragment.java
> -        }
@gsantner Please note that I removed this existing code as it didn't seem to do anything useful.

2020-10-15 16:12 UTC, gsantner commented
does it also work when changing the format when being in the editor? I.e. do the correct actions show up in correct format, for new selected format?

2020-10-15 16:17 UTC, harshad1 commented
Yes. Works in both the editor when changing formats and when switching tabs in the main screen.

Oct. 15, 2020 09:13:20 Gregor Santner <notifications@github.com>:

> does it also work when changing the format when being in the editor? I.e. do the correct actions show up in correct format, for new selected format?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[https://github.com/gsantner/markor/pull/1087#issuecomment-709432760], or unsubscribe[https://github.com/notifications/unsubscribe-auth/AAOZ3TBP34KIRC4VMO7J5IDSK4NR5ANCNFSM4SMJC6GQ]. [https://github.com/notifications/beacon/AAOZ3THGRH5FYKXY6X5NDHLSK4NR5A5CNFSM4SMJC6G2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFJERLOA.gif]
>

2020-10-16 10:46 UTC, merged

2020-10-16 10:46 UTC, gsantner commented
thx mergeed

2020-11-13 16:50 UTC, gsantner commented
@harshad1 
due new device, new markor installation.

I found that the Markdown actions order is different than was previously (random?). Can you check that?

2020-11-13 17:59 UTC, harshad1 commented
@gsantner Hmm I think I see the issue

It is here
https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/ui/hleditor/TextActions.java#L211-L212

This code has been like this for a while now (since the initial reorder actions change)

To fix this we just need to change the HashSets to ordered sets. I can do this in my search / replace pr or I can make a new PR.

2020-11-13 18:17 UTC, gsantner commented
however you prefer