Keep in-files search dialog open
gsantner/markor pull request #1689
Opened 2022-04-29 04:37 UTC by harshad1

This PR adds the following features to the in-files search results:

1. The dialog will stay open when an item is clicked. Can return to main via back or recent apps and open another file.
2. The file names (group names) have been made bold
3. Long clicking the file name will take you to the top of the file

2022-04-29 21:00 UTC, gsantner requested changes

2022-04-29 21:00 UTC, gsantner commented on app/src/main/java/net/gsantner/markor/ui/fsearch/FileSearchResultSelectorDialog.java
> +            textView.setText(Html.fromHtml(String.format("<b>%s</b>", groupInfo.toString())));
%s string needs to be XML/HTML encoded otherwise might render wrong

2022-05-21 09:26 UTC, gsantner approved these changes
thanks works good

remove the bold though..it was just everything bold - too much. But generally the dialog and it's contents could be a bit face-lifted wording improved / better styled :smile: .

2022-05-21 09:30 UTC, merged

2024-05-01 05:56 UTC, Adirlearn-dev12 reviewed
Me sorprendió la app