fixes #1428 by introducing a new color picker
gsantner/markor pull request #2203
Opened 2024-01-11 14:39 UTC by halfdane

1. Introduces [martin stone's colorpicker](https://github.com/martin-stone/hsv-alpha-color-picker-android) as a replacement for quadflask's.
2. Removes the obsolete 3rd-party quadflask code 
3. Removes an unused method with a dependency to the quadflask code
4. Bumps the minSDK from 16 to 18

Since I'm not intimately familiar with this code (or any android code), please make sure I didn't inadvertently breack stuff with the removal of (probably?) unused code or the version bump.

2024-01-11 19:11 UTC, gsantner commented
Hello thank you for your help!

As you asking about breaking, these things are especially important to work: Color picking at editor (insert color i.e.) and at the settings (picking background color in basic scheme for example).

2024-01-12 08:56 UTC, halfdane commented
I have checked that the picker works correctly in basic color scheme settings, but that seems to be the only place where a color picker is used: I don't know how to do "Color picking at editor (insert color i.e.)", so if you could point me to the right place in the UI, I'll gladly check.

2024-02-16 04:30 UTC, gsantner requested changes

2024-02-16 04:30 UTC, gsantner commented on app/src/main/res/xml/preferences_master.xml
> -                android:title="@string/link_color" />
This settings option is currently missing in the updated code/new colorpicker.

2024-02-16 04:34 UTC, gsantner commented
> I have checked that the picker works correctly in basic color scheme settings, but that seems to be the only place where a color picker is used: I don't know how to do "Color picking at editor (insert color i.e.)", so if you could point me to the right place in the UI, I'll gladly check.

There was a "Attachment" button and dialog, which currently seems to be removed or at last doesn't work. There were quite a few changes on that part recently and it's being reworked.

The pooint is, the new library support that - just showing a color picker dialog and get the color string out, so it can be inserted in the text document?

2024-02-16 04:35 UTC, gsantner commented
> I have checked that the picker works correctly in basic color scheme settings, but that seems to be the only place where a color picker is used: I don't know how to do "Color picking at editor (insert color i.e.)", so if you could point me to the right place in the UI, I'll gladly check.

There was a "Attachment" button and dialog, which currently seems to be removed or at last doesn't work. There were quite a few changes on that part recently and it's being reworked.

The point is, does the new library support showing a color picker dialog and get the color string out, so it can be inserted in the text document?

2024-03-27 02:17 UTC, gsantner commented
Want to merge this after the upcoming update, so it still goes by the old minsdk version and the big mass of changes reaches also users with old devices.

2024-05-10 05:51 UTC, harshad1 commented on app/build.gradle
> +rootProject.ext.version_minSdk = 18
There are a bunch of

` if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) { `

in our codebase. May be good to remove them if we are bumping versions

2024-07-27 10:43 UTC, gsantner commented on app/src/main/res/xml/preferences_master.xml
> -                android:title="@string/link_color" />
I restored it self, pushed to PR branch

2024-07-27 11:24 UTC, gsantner approved these changes
Thank you, it's time to drop the dated color picker. Merging

2024-07-27 11:25 UTC, merged